In [5]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [6]:
dataset = pd.read_csv("customized_daily_rainfall_data.csv")

In [7]:
dataset

StationIndex  Year  Month  Day  Rainfall
0                  1  1970      1    1         0
1                  1  1970      1    2         0
2                  1  1970      1    3         0
3                  1  1970      1    4         0
4                  1  1970      1    5         0
...              ...   ...    ...  ...       ...
542371            35  2016     12   27         0
542372            35  2016     12   28         0
542373            35  2016     12   29         0
542374            35  2016     12   30         0
542375            35  2016     12   31         0

[542376 rows x 5 columns]

In [8]:
dataset.describe()

StationIndex           Year          Month           Day  \
count  542376.000000  542376.000000  542376.000000  542376.00000   
mean       17.793553    1994.757888       6.500000      16.00000   
std        10.012240      13.115871       3.452056       8.94428   
min         1.000000    1970.000000       1.000000       1.00000   
25%         9.000000    1984.000000       3.750000       8.00000   
50%        18.000000    1995.000000       6.500000      16.00000   
75%        26.000000    2006.000000       9.250000      24.00000   
max        35.000000    2016.000000      12.000000      31.00000   

            Rainfall  
count  542376.000000  
mean        6.432772  
std        19.000804  
min         0.000000  
25%         0.000000  
50%         0.000000  
75%         2.000000  
max       590.000000

In [9]:
X = dataset.iloc[:,:-1].values

In [10]:
X

array([[   1, 1970,    1,    1],
       [   1, 1970,    1,    2],
       [   1, 1970,    1,    3],
       ...,
       [  35, 2016,   12,   29],
       [  35, 2016,   12,   30],
       [  35, 2016,   12,   31]])

In [11]:
y = dataset.iloc[:,-1].values

In [12]:
y

array([0, 0, 0, ..., 0, 0, 0])

In [13]:
from sklearn.model_selection import train_test_split

In [19]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3)

In [20]:
X_train

array([[  24, 1996,    3,    3],
       [  15, 2008,   11,   19],
       [  15, 1985,    8,    3],
       ...,
       [  18, 1994,    6,   12],
       [   9, 1988,    4,   23],
       [   2, 2003,    4,   28]])

In [21]:
X_test

array([[  28, 2009,    5,    9],
       [  27, 1975,   10,   31],
       [  33, 1971,   11,    4],
       ...,
       [  17, 1995,    2,    5],
       [  24, 1998,    6,   29],
       [   1, 1976,   12,    5]])

In [22]:
y_train

array([ 0,  0, 50, ..., 16,  0,  5])

In [23]:
y_test

array([ 0, 15,  0, ...,  0, 12,  0])

In [24]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion="entropy", random_state=0)
classifier.fit(X_train, y_train)

DecisionTreeClassifier(criterion='entropy', random_state=0)

In [28]:
classifier.predict([[   2, 2003,    4,   28]])

array([5])

In [29]:
y_pred = classifier.predict(X_test)

In [30]:
y_pred

array([ 0,  0, 38, ...,  0,  3,  0])

In [33]:
np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1)

array([[ 0,  0],
       [ 0, 15],
       [38,  0],
       ...,
       [ 0,  0],
       [ 3, 12],
       [ 0,  0]])

In [34]:
from sklearn.metrics import confusion_matrix, accuracy_score

In [35]:
cm = confusion_matrix(y_test, y_pred)

In [36]:
cm

array([[94473,  2705,  1778, ...,     0,     0,     0],
       [ 2113,   480,   290, ...,     0,     0,     0],
       [ 1427,   326,   235, ...,     0,     0,     0],
       ...,
       [    0,     0,     0, ...,     0,     0,     0],
       [    0,     0,     0, ...,     0,     0,     0],
       [    0,     0,     0, ...,     0,     0,     0]])

In [37]:
accuracy_score(y_test, y_pred)

0.5899528617873188