In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [9]:
dataset = pd.read_csv("customized_daily_rainfall_data.csv")

In [3]:
dataset

StationIndex  Year  Month  Day  Rainfall
0                  1  1970      1    1         0
1                  1  1970      1    2         0
2                  1  1970      1    3         0
3                  1  1970      1    4         0
4                  1  1970      1    5         0
...              ...   ...    ...  ...       ...
542371            35  2016     12   27         0
542372            35  2016     12   28         0
542373            35  2016     12   29         0
542374            35  2016     12   30         0
542375            35  2016     12   31         0

[542376 rows x 5 columns]

In [4]:
X = dataset.iloc[:,:-1].values

In [5]:
X

array([[   1, 1970,    1,    1],
       [   1, 1970,    1,    2],
       [   1, 1970,    1,    3],
       ...,
       [  35, 2016,   12,   29],
       [  35, 2016,   12,   30],
       [  35, 2016,   12,   31]])

In [6]:
y = dataset.iloc[:,-1].values

In [7]:
y

array([0, 0, 0, ..., 0, 0, 0])

In [10]:
from sklearn.model_selection import train_test_split

In [11]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3)

In [12]:
X_train

array([[  27, 1978,    7,    1],
       [  15, 1989,    1,    1],
       [  12, 2015,   12,   23],
       ...,
       [  11, 1979,    6,   14],
       [  20, 1978,    6,   13],
       [  21, 1988,    9,    6]])

In [13]:
X_test

array([[  15, 1987,    9,   19],
       [   9, 1971,    7,   27],
       [   8, 2013,    7,   13],
       ...,
       [   5, 2002,   10,   13],
       [  26, 1971,   10,    6],
       [  13, 2001,    1,   23]])

In [14]:
y_train

array([ 0,  0,  0, ...,  6,  0, 38])

In [15]:
y_test

array([ 0,  0,  9, ...,  0, 18,  1])

In [17]:
from sklearn.ensemble import RandomForestClassifier

In [41]:
classifier = RandomForestClassifier(n_estimators = 100, criterion="entropy", random_state=0)
classifier.fit(X_train, y_train)

RandomForestClassifier(criterion='entropy', random_state=0)

In [42]:
classifier.predict([[  13, 2001,    1,   23]])

array([0])

In [43]:
y_pred = classifier.predict(X_test)

In [44]:
y_pred

array([0, 0, 0, ..., 0, 0, 0])

In [45]:
np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1)

array([[ 0,  0],
       [ 0,  0],
       [ 0,  9],
       ...,
       [ 0,  0],
       [ 0, 18],
       [ 0,  1]])

In [46]:
from sklearn.metrics import confusion_matrix, accuracy_score

In [47]:
cm = confusion_matrix(y_test, y_pred)

In [48]:
cm

array([[107036,    960,    619, ...,      0,      0,      0],
       [  3783,    320,    193, ...,      0,      0,      0],
       [  2610,    189,    136, ...,      0,      0,      0],
       ...,
       [     0,      0,      0, ...,      0,      0,      0],
       [     1,      0,      0, ...,      0,      0,      0],
       [     0,      1,      0, ...,      0,      0,      0]])

In [49]:
accuracy_score(y_test, y_pred)

0.6633458912318008