In [4]:
import numpy as np

In [2]:
list1 = [1,2,4,5]

In [3]:
list1

[1, 2, 4, 5]

In [4]:
arr1 = np.array(list1)

In [5]:
arr1

array([1, 2, 4, 5])

In [2]:
list2 = [[1,2,3],[2,3,4],[2,3,4]]

In [9]:
list2

[[1, 2, 3], [2, 3, 4], [2, 3, 4]]

In [5]:
arr2 = np.array(list2)

In [11]:
arr2

array([[1, 2, 3],
       [2, 3, 4],
       [2, 3, 4]])

In [12]:
list3 = [[1, 2, 3], [2, 3, 4], [2, 3]]

In [13]:
arr3 = np.array(list3)

/var/folders/4d/3wv1h89n3pqg97k6l642djzh0000gn/T/ipykernel_17245/550351161.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  arr3 = np.array(list3)


In [14]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
np.arange(0,100,9)

array([ 0,  9, 18, 27, 36, 45, 54, 63, 72, 81, 90, 99])

In [19]:
np.zeros(3)

array([0., 0., 0.])

In [20]:
np.ones(4)

array([1., 1., 1., 1.])

In [23]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [25]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [30]:
np.linspace(1, 100)

array([  1.        ,   3.02040816,   5.04081633,   7.06122449,
         9.08163265,  11.10204082,  13.12244898,  15.14285714,
        17.16326531,  19.18367347,  21.20408163,  23.2244898 ,
        25.24489796,  27.26530612,  29.28571429,  31.30612245,
        33.32653061,  35.34693878,  37.36734694,  39.3877551 ,
        41.40816327,  43.42857143,  45.44897959,  47.46938776,
        49.48979592,  51.51020408,  53.53061224,  55.55102041,
        57.57142857,  59.59183673,  61.6122449 ,  63.63265306,
        65.65306122,  67.67346939,  69.69387755,  71.71428571,
        73.73469388,  75.75510204,  77.7755102 ,  79.79591837,
        81.81632653,  83.83673469,  85.85714286,  87.87755102,
        89.89795918,  91.91836735,  93.93877551,  95.95918367,
        97.97959184, 100.        ])

In [31]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [32]:
np.random.rand(2)

array([0.51696887, 0.86565009])

In [33]:
list = [1,2,3,4,5,6,7,8]

In [34]:
ar = np.array(list)

In [35]:
ar

array([1, 2, 3, 4, 5, 6, 7, 8])

In [36]:
ar[0]

1

In [37]:
ar[7]

8

In [38]:
ar[-1]

8

In [40]:
ar[1:3]

array([2, 3])

In [41]:
ar[2:]

array([3, 4, 5, 6, 7, 8])

In [42]:
ar[:6]

array([1, 2, 3, 4, 5, 6])

In [43]:
ar[10]

IndexError: index 10 is out of bounds for axis 0 with size 8

In [44]:
ar.max()

8

In [45]:
ar.min()

1

In [46]:
ar.mean()

4.5

In [47]:
arr2

array([[1, 2, 3],
       [2, 3, 4],
       [2, 3, 4]])

In [52]:
arr2[2][2]

4

In [53]:
arr2[2][0:]

array([2, 3, 4])

In [55]:
arr2[:1][:1]

array([[1, 2, 3]])

In [60]:
arr2[:1][:1]

array([[1, 2, 3]])

In [61]:
arr2[1][1]

3

In [62]:
arr2[:1][:1]

array([[1, 2, 3]])

In [64]:
arr2[:2]

array([[1, 2, 3],
       [2, 3, 4]])

In [71]:
arr2[2][0]

2

In [74]:
array2 = np.zeros((0,10))

In [75]:
array2

array([], shape=(0, 10), dtype=float64)

In [76]:
for i in range(array2):
    array2[i] = 1
    


TypeError: only integer scalar arrays can be converted to a scalar index

In [77]:
array2.dtype

dtype('float64')

In [78]:
arr = np.ones((4,4))

In [79]:
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [83]:
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [84]:
arr_length = arr.shape[1]

In [87]:
for i in range(arr_length):
    arr[i] = 10

In [88]:
arr

array([[10., 10., 10., 10.],
       [10., 10., 10., 10.],
       [10., 10., 10., 10.],
       [10., 10., 10., 10.]])

In [8]:
arr = np.zeros((10,10))

In [90]:
arr

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [91]:
arr_length = arr.shape[1]

In [92]:
arr_length

10

In [93]:
arr[2] = 1

In [94]:
arr

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [2]:
from numpy.random import randn

In [3]:
randn(5,4)

array([[-0.62329871,  0.44420927, -0.1306009 ,  0.35549135],
       [ 2.38158654, -0.94323011, -0.37625601,  0.00858555],
       [ 0.06642792,  1.03371096,  1.58117875, -0.03029945],
       [ 0.47453447,  0.66411341, -0.32673945,  1.18501358],
       [ 0.87795176, -0.86145828,  0.06001742,  0.65771922]])

In [4]:
arr>0

NameError: name 'arr' is not defined

In [24]:
arr2 = np.array(list2)

In [6]:
arr2

array([[1, 2, 3],
       [2, 3, 4],
       [2, 3, 4]])

In [8]:
arr2[2,2]

4

In [9]:
arr2[1,1]

3

In [10]:
arr2[:2,:2]

array([[1, 2],
       [2, 3]])