In [1]:
import pandas as pd

## Series

In [2]:
list = [1,2,3,4,5]

In [3]:
pd.Series(data=list)

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [4]:
list1 = [1.0, 2.0, 3.0, 4.0, 5.0]

In [6]:
pd.Series(data=list1)

0    1.0
1    2.0
2    3.0
dtype: float64

In [7]:
import numpy as np

In [11]:
arr = np.array([1,2,3])

In [12]:
arr

array([1, 2, 3])

In [13]:
pd.Series(data=arr)

0    1
1    2
2    3
dtype: int64

In [14]:
list2 = ['hi', 'how', 'are']

In [15]:
pd.Series(data=list2)

0     hi
1    how
2    are
dtype: object

In [17]:
pd.Series(data=list1, index=list2)

hi     1.0
how    2.0
are    3.0
dtype: float64

In [19]:
list3 = [1.0, 2.0, 3.0, 4.0, 5.0]

In [20]:
pd.Series(data=list, index=list3)

1.0    1
2.0    2
3.0    3
4.0    4
5.0    5
dtype: int64

In [21]:
pd.Series(list,list3)

1.0    1
2.0    2
3.0    3
4.0    4
5.0    5
dtype: int64

In [22]:
pd.Series(list3)

0    1.0
1    2.0
2    3.0
3    4.0
4    5.0
dtype: float64

In [23]:
d = {'one': 1, 'two': 2, "three": 3, "four": 4}

In [24]:
d

{'one': 1, 'two': 2, 'three': 3, 'four': 4}

In [25]:
pd.Series(d)

one      1
two      2
three    3
four     4
dtype: int64

In [26]:
list1

[1.0, 2.0, 3.0]

In [27]:
pd.Series(list1,index = ['a','b','c'])

a    1.0
b    2.0
c    3.0
dtype: float64

In [28]:
list = ['a','b','c']

In [29]:
list = 'a b c'.split()

In [30]:
list

['a', 'b', 'c']

In [31]:
list = 'a /b /c'.split('/')

In [32]:
list

['a ', 'b ', 'c']

In [33]:
list = 'a 1/b 2/c 3'.split('/')

In [34]:
list

['a 1', 'b 2', 'c 3']

In [36]:
ser1 = pd.Series(data=[1,2,3,4], index=['football','cricket','hockey','basketball'])

In [37]:
ser1

football      1
cricket       2
hockey        3
basketball    4
dtype: int64

In [38]:
ser2 = pd.Series(data=[1,1,1,1], index=['football','cricket','baseball','basketball'])

In [39]:
ser2

football      1
cricket       1
baseball      1
basketball    1
dtype: int64

In [40]:
ser1 + ser2

baseball      NaN
basketball    5.0
cricket       3.0
football      2.0
hockey        NaN
dtype: float64

## Data Frames

In [41]:
from numpy.random import randn

In [42]:
randn(1,1)

array([[1.15349665]])

In [43]:
randn(4,4)

array([[-1.08501589, -0.82242158,  0.3654426 , -0.35166261],
       [ 0.36513703,  0.27139436,  0.50049273, -0.63721587],
       [ 1.68735753,  0.97501501,  0.06489149, -0.03242335],
       [ 2.11524505,  0.29278596,  0.87013934,  0.03352875],
       [ 1.38416268,  0.01932728, -0.15667337, -0.22323096]])

In [121]:
df = pd.DataFrame(randn(5,4), index=['a','b','c', 'd', 'e'], columns='S T U V'.split())

In [60]:
df

S         T         U         V
a -0.928653  0.185737 -0.915208 -1.529930
b  0.160719  0.701901 -1.178312 -1.777081
c  0.332804 -1.338149 -0.508958  1.357197
d -0.255154  0.948677  0.713564  0.146680
e  0.101504 -0.773761  1.200522 -1.192379

In [47]:
df['S']

a    0.011508
b   -0.362569
c   -2.111459
d    2.177542
e    1.707808
Name: S, dtype: float64

In [48]:
df[['S','U']]

S         U
a  0.011508 -0.782949
b -0.362569  0.064876
c -2.111459  1.137392
d  2.177542  0.242788
e  1.707808  1.417513

In [61]:
df > 0

S      T      U      V
a  False   True  False  False
b   True   True  False  False
c   True  False  False   True
d  False   True   True   True
e   True  False   True  False

In [63]:
df

S         T         U         V
a -0.928653  0.185737 -0.915208 -1.529930
b  0.160719  0.701901 -1.178312 -1.777081
c  0.332804 -1.338149 -0.508958  1.357197
d -0.255154  0.948677  0.713564  0.146680
e  0.101504 -0.773761  1.200522 -1.192379

In [62]:
df[df>0]

S         T         U         V
a       NaN  0.185737       NaN       NaN
b  0.160719  0.701901       NaN       NaN
c  0.332804       NaN       NaN  1.357197
d       NaN  0.948677  0.713564  0.146680
e  0.101504       NaN  1.200522       NaN

In [64]:
df.S

a   -0.928653
b    0.160719
c    0.332804
d   -0.255154
e    0.101504
Name: S, dtype: float64

In [68]:
df['new'] = df.S + df.U

In [69]:
df

S         T         U         V       new
a -0.928653  0.185737 -0.915208 -1.529930 -1.843861
b  0.160719  0.701901 -1.178312 -1.777081 -1.017594
c  0.332804 -1.338149 -0.508958  1.357197 -0.176154
d -0.255154  0.948677  0.713564  0.146680  0.458410
e  0.101504 -0.773761  1.200522 -1.192379  1.302026

In [67]:
df['new']

a   -1.843861
b   -1.017594
c   -0.176154
d    0.458410
e    1.302026
Name: new, dtype: float64

In [78]:
df.U

a   -0.915208
b   -1.178312
c   -0.508958
d    0.713564
e    1.200522
Name: U, dtype: float64

In [71]:
df.loc['a']

S     -0.928653
T      0.185737
U     -0.915208
V     -1.529930
new   -1.843861
Name: a, dtype: float64

In [79]:
df.loc['b']['U']

-1.1783123678298428

In [89]:
df >0

S      T      U      V    new
a  False   True  False  False  False
b   True   True  False  False  False
c   True  False  False   True  False
d  False   True   True   True   True
e   True  False   True  False   True

In [81]:
df[df>0]

S         T         U         V       new
a       NaN  0.185737       NaN       NaN       NaN
b  0.160719  0.701901       NaN       NaN       NaN
c  0.332804       NaN       NaN  1.357197       NaN
d       NaN  0.948677  0.713564  0.146680  0.458410
e  0.101504       NaN  1.200522       NaN  1.302026

In [86]:
df[df['T']>0]['T']

a    0.185737
b    0.701901
d    0.948677
Name: T, dtype: float64

In [90]:
df

S         T         U         V       new
a -0.928653  0.185737 -0.915208 -1.529930 -1.843861
b  0.160719  0.701901 -1.178312 -1.777081 -1.017594
c  0.332804 -1.338149 -0.508958  1.357197 -0.176154
d -0.255154  0.948677  0.713564  0.146680  0.458410
e  0.101504 -0.773761  1.200522 -1.192379  1.302026

In [92]:
df['mean'] = df.S + df['T'] + df.U + df.V

In [93]:
df

S         T         U         V       new      mean
a -0.928653  0.185737 -0.915208 -1.529930 -1.843861 -3.188054
b  0.160719  0.701901 -1.178312 -1.777081 -1.017594 -2.092773
c  0.332804 -1.338149 -0.508958  1.357197 -0.176154 -0.157106
d -0.255154  0.948677  0.713564  0.146680  0.458410  1.553767
e  0.101504 -0.773761  1.200522 -1.192379  1.302026 -0.664114

In [99]:
df['mean']>0

a    False
b    False
c    False
d     True
e    False
Name: mean, dtype: bool

In [101]:
df[df['mean']<0]

S         T         U         V       new      mean
a -0.928653  0.185737 -0.915208 -1.529930 -1.843861 -3.188054
b  0.160719  0.701901 -1.178312 -1.777081 -1.017594 -2.092773
c  0.332804 -1.338149 -0.508958  1.357197 -0.176154 -0.157106
e  0.101504 -0.773761  1.200522 -1.192379  1.302026 -0.664114

In [102]:
df

S         T         U         V       new      mean
a -0.928653  0.185737 -0.915208 -1.529930 -1.843861 -3.188054
b  0.160719  0.701901 -1.178312 -1.777081 -1.017594 -2.092773
c  0.332804 -1.338149 -0.508958  1.357197 -0.176154 -0.157106
d -0.255154  0.948677  0.713564  0.146680  0.458410  1.553767
e  0.101504 -0.773761  1.200522 -1.192379  1.302026 -0.664114

In [122]:
dataf1 = df[df>0]

In [104]:
dataf1

S         T         U         V       new      mean
a       NaN  0.185737       NaN       NaN       NaN       NaN
b  0.160719  0.701901       NaN       NaN       NaN       NaN
c  0.332804       NaN       NaN  1.357197       NaN       NaN
d       NaN  0.948677  0.713564  0.146680  0.458410  1.553767
e  0.101504       NaN  1.200522       NaN  1.302026       NaN

In [105]:
dataf1.fillna(value = "Not available")

S              T              U              V            new  \
a  Not available       0.185737  Not available  Not available  Not available   
b       0.160719       0.701901  Not available  Not available  Not available   
c       0.332804  Not available  Not available       1.357197  Not available   
d  Not available       0.948677       0.713564        0.14668        0.45841   
e       0.101504  Not available       1.200522  Not available       1.302026   

            mean  
a  Not available  
b  Not available  
c  Not available  
d       1.553767  
e  Not available

In [107]:
dataf1.loc['d']['S']=0.1

In [108]:
dataf1

S         T         U         V       new      mean
a       NaN  0.185737       NaN       NaN       NaN       NaN
b  0.160719  0.701901       NaN       NaN       NaN       NaN
c  0.332804       NaN       NaN  1.357197       NaN       NaN
d  0.100000  0.948677  0.713564  0.146680  0.458410  1.553767
e  0.101504       NaN  1.200522       NaN  1.302026       NaN

In [118]:
dataf1.dropna(inplace=True)

In [120]:
dataf1

S         T         U        V      new      mean
d  0.1  0.948677  0.713564  0.14668  0.45841  1.553767